### ISSUE TITLE
Instead of 5 star rating, use 10 star rating like themoviedb.org and imdb uses

### ISSUE THREAD

**Issue by GoogleCodeExporter** [damienhaynes/moving-pictures#1103]
```
Instead of 5 star rating, use 10 star rating like themoviedb.org and imdb uses
```

Original issue reported on code.google.com by `pe...@sluth.dk` on 20 Oct 2012 at 3:50

**Comment by damienhaynes** [comment]
Added db field to store 10 point scale, closing this issue as you can use the trakt plugin to rate movies in a 10 point scale.
