### ISSUE TITLE
The Dialog presented to user when MovingPictures isn't configured needs some work

### ISSUE THREAD

**Issue by GoogleCodeExporter** [damienhaynes/moving-pictures#870]
```
The Dialog presented to user when MovingPictures isn't configured needs some 
work. The Labels could be more wider before creating a newline.

See Attachment for illustration.
```

Original issue reported on code.google.com by `damien.haynes@gmail.com` on 26 Jul 2010 at 1:51

Attachments:
* [MovingPicturesNotConfiguredDialog.jpg](https://storage.googleapis.com/google-code-attachments/moving-pictures/issue-870/comment-0/MovingPicturesNotConfiguredDialog.jpg)

**Comment by damienhaynes** [comment]
Done.
